name: capstonedesign

description: "capstonedesign project"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

# The environment specifies the minimum Flutter SDK version required to run the app.
environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Firebase core services
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  firebase_database: ^10.4.0
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5

  # Media and image handling
  image_picker: ^1.0.7


  # Google sign-in support
  google_sign_in: ^6.0.1

  # Internationalization (used for DateFormat)
  intl: ^0.18.1

  # Cupertino icons for iOS style widgets
  cupertino_icons: ^1.0.8

# Development-only dependencies
# These packages are only used during development and testing.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint rules for enforcing coding standards
  flutter_lints: ^5.0.0

# Flutter-specific settings
flutter:
  # Ensures Material Icons font is available in the app
  uses-material-design: true

  # Assets used in the application
  assets:
    - assets/images/image_firstpage_login.png
    - assets/images/image_app_homepage.png
    - assets/images/image_app_start.png
    - assets/images/image_plogging_sample.jpg
    - assets/images/image_google_icon.png

  # To add fonts, uncomment and configure the following:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

