// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCATEwwZxPzVSVzKHGZhAqN2YPdxmbT5Fs',
    appId: '1:931926634118:web:4b787409c57ca01a9aeb07',
    messagingSenderId: '931926634118',
    projectId: 'capstone3jo-2b5b7',
    authDomain: 'capstone3jo-2b5b7.firebaseapp.com',
    databaseURL: 'https://capstone3jo-2b5b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone3jo-2b5b7.firebasestorage.app',
    measurementId: 'G-2LVS3Y73V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkK5t5P_ghWoW_8xj79q0o7HfnsoKDcXk',
    appId: '1:931926634118:android:6d0f06acac986bbc9aeb07',
    messagingSenderId: '931926634118',
    projectId: 'capstone3jo-2b5b7',
    databaseURL: 'https://capstone3jo-2b5b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone3jo-2b5b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3kyBifNKdYntPO7Tk7yHp-7_yWG0id-8',
    appId: '1:931926634118:ios:b377b158ec91cf039aeb07',
    messagingSenderId: '931926634118',
    projectId: 'capstone3jo-2b5b7',
    databaseURL: 'https://capstone3jo-2b5b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone3jo-2b5b7.firebasestorage.app',
    iosBundleId: 'com.dev.capstone.capstonedesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3kyBifNKdYntPO7Tk7yHp-7_yWG0id-8',
    appId: '1:931926634118:ios:b377b158ec91cf039aeb07',
    messagingSenderId: '931926634118',
    projectId: 'capstone3jo-2b5b7',
    databaseURL: 'https://capstone3jo-2b5b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone3jo-2b5b7.firebasestorage.app',
    iosBundleId: 'com.dev.capstone.capstonedesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCATEwwZxPzVSVzKHGZhAqN2YPdxmbT5Fs',
    appId: '1:931926634118:web:57051a9cb763df759aeb07',
    messagingSenderId: '931926634118',
    projectId: 'capstone3jo-2b5b7',
    authDomain: 'capstone3jo-2b5b7.firebaseapp.com',
    databaseURL: 'https://capstone3jo-2b5b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone3jo-2b5b7.firebasestorage.app',
    measurementId: 'G-VXGT6MZ78R',
  );

}